!     -*- f90 -*-
!     This file is autogenerated with f2py (version:2)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinitkinds_module(f2pysetupfunc)
      use kinds_module, only : test_double
      use kinds_module, only : test_complex
      external f2pysetupfunc
      call f2pysetupfunc(test_double,test_complex)
      end subroutine f2pyinitkinds_module

      
      subroutine f2pyinitbhmie_module(f2pysetupfunc)
      use bhmie_module, only : bhmie_driver
      external f2pysetupfunc
      call f2pysetupfunc(bhmie_driver)
      end subroutine f2pyinitbhmie_module

      
      subroutine f2pyinitdmiess_module(f2pysetupfunc)
      use dmiess_module, only : dmiess_driver
      external f2pysetupfunc
      call f2pysetupfunc(dmiess_driver)
      end subroutine f2pyinitdmiess_module

      
      subroutine f2pyinitdmilay_module(f2pysetupfunc)
      use dmilay_module, only : dmilay_driver
      external f2pysetupfunc
      call f2pysetupfunc(dmilay_driver)
      end subroutine f2pyinitdmilay_module


